title: Thomas Camboulas
subtitle: PortFolio
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenue sur mon PortFolio :D

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Accueil
      url: /
    - text: À propos de moi
      url: /about
    - text: Mon entreprise
      url: /MonEntreprise
    - text: Mes projets
      url: /projet
    - text: Ma veille
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: PhotoProfil.png
author: Thomas Camboulas
author_bio: |
  Je m'appelle Thomas Camboulas, étudiant en BTS Services Informatiques aux Organisations (SIO) avec une spécialisation en Solutions Logicielles et Applications Métiers (SLAM). Actuellement en alternance, je me consacre pleinement à acquérir des compétences pratiques et théoriques dans le domaine de l'informatique.
  
  Mon parcours académique a été marqué par une passion croissante pour le développement logiciel et les technologies de l'information. Mon cursus en BTS SIO SLAM me permet de développer des compétences solides en programmation, en gestion de bases de données, et en analyse. En alternance, j'ai pu mettre en pratique ces connaissances au sein de l'entreprise, ce qui a considérablement enrichi mon expérience professionnelle. Mon ambition est de poursuivre mes études pour devenir ingénieur en informatique.
  
  Je suis convaincu que ce parcours me permettra de maîtriser les technologies de pointe et de participer à des projets innovants comme le développement de l’intelligence artificielle. Je souhaite contribuer à la création de solutions logicielles efficaces et à l'amélioration des systèmes d'information.

author_email: "camboulasthomas@gmail.com"
author_location: France
author_website_url: "https://thomascbls.github.io/#/"
typewrite-text: Bienvenue sur mon portfolio :D
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: MTB111
              company_logo: mtb111.png
              company_url: https://www.mtb-generative.com/
              designation: Analyste-Programmeur
              description: Utilisation de divers langages pour developper et debugger un logiciel ou une application.
              visibility: true
            - company_name: SOCOPA
              company_logo: socopa.png
              company_url: https://www.socopa.fr/
              designation: Technicien de maintenance dans les énergies
              description: Assurer l'entretien, le dépannage et l'optimisation des équipements et installations liés aux systèmes de production, de distribution et de stockage d'énergie, pour garentir leur bon fonctionnement et leur conformité aux normes de sécurité.
              visibility: true
            - company_name: McDonald's
              company_logo: macdo.png
              company_url: https://www.mcdonalds.fr/
              designation: Équipier
              description: Assurer la préparation des commandes, le service à la clientèle, le nettoyage et l'entretien de l'espace de travail, contribuant ainsi à l'efficacité et à la satisfaction des clients.
              visibility: true

# Education
author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                icon: 3ifa.png
                visibility: false
              - college_logo: mit.png
                college_name: 3IFA
                college_url: https://www.3ifa.fr/
                college_degree: Alternant BTS SIO
                description: BTS SIO option SLAM
                icon: 3ifa.png
                visibility: true
              - college_logo: mit.png
                college_name: Bâtiment CFA Alençon
                college_url: https://www.batimentcfanormandie.fr/le-reseau/nos-centres-de-formations/batiment-cfa-alencon/
                college_degree: Alternant BTS FED
                description: BTS FED option Domotique (1 année)
                icon: CFA.png
                visibility: true
              - college_logo: /assets/img/lycee.png
                college_name: Lycée Robert Garnier
                college_url: https://robert-garnier.paysdelaloire.e-lyco.fr/
                college_degree: BAC STI2D
                description: BAC STI2D option Energie et Environnement
                icon: lycee.png
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: hack4r.PNG
                project_title: Workflow sécurisé
                project_description: Project réalisé en période d'entreprise. Ce projet répond aux besoins interne de l'entreprise qui ne possède pas d'application web pour réaliser ses demandes de congées, de charges mensuelles ainsi que de notes de frais. Alors nous avons réalisé de A à Z une application web répondant aux critères du client.
                icon : logoWks.png
                visibility: true
                year: second
              - project_thumbnail: hack4r.PNG
                project_title: RFTG
                project_description: Project réalisé en période scolaire. Ce projet répond à un besoin de location de DVD dans un village vacance. Pour cela nous avons un webservice qui fait l'intermédiaire entre la base de données et notre application web et mobile.
                icon : logoRftg.png
                visibility: true
                year: second
              - project_thumbnail: hack4r.PNG
                project_title: ETHORYAM
                project_description: Project réalisé en période scolaire. Ce projet a pour but de créer une application qui avec un raccourcis clavier de touche défini (par exemple A + Z+ E), organisant une réunion d'urgence. L'application enverra une notification accompagnée d'une sonorité qui alerterait les utilisateurs sélectionnés au préalable pour rejoindre la réunion. La notification d'urgence donnera l'information du titre de la réunion ainsi que le lieu.
                icon : ethoryam.png
                visibility: true
                year: first 
              - project_thumbnail: hack4r.PNG
                project_title: VTT
                project_description: Projet réalisé en période d'entreprise. VTT est une application permettant de réaliser des tests automatisés, mon rôle au seins de ce projet était de faire du ticketing pour régler divers problèmes.
                icon : vtt.png
                visibility: true
                year: first # Affecté à la première année


# social links
github_username: ThomasCbls
linkedin_username: thomas-camboulas-88a5b6310
cv_username: CV THOMAS.pdf

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: camboulasthomas@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: MTB111
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
